IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_START_HEIGHT: 400
  ROI_HEIGHT: 50

XYCAR:
  START_SPEED: 0.0
  MAX_SPEED: 5.0
  MIN_SPEED: 5.0
  SPEED_CONTROL_THRESHOLD: 15.0
  ACCELERATION_STEP: 0.05
  DECELERATION_STEP: 0.1
  LINEAR_UNIT: 10
  ANGLE_UNIT: 1

PID:
  P_GAIN: 0.36
  I_GAIN: 0.0006
  D_GAIN: 0.08

STANLEY:
  K_GAIN: 0.06
  LOOK_AHREAD_DISTANCE: 0.2

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 30

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

CANNY:
  LOW_THRESHOLD: 150
  HIGH_THRESHOLD: 250

HOUGH:
  ABS_SLOPE_RANGE: 10.0
  THRESHOLD: 15
  MIN_LINE_LENGTH: 20
  MAX_LINE_GAP: 10
  CONTINUS_THRESHOLD: 60

DEBUG: false
